# Site settings
title: Kazunari Tanabe
email: k.tanabe2@lse.ac.uk

# Build settings
markdown: kramdown
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Navigation menu
header_pages:
  - research.md
  - cv.md
